### ISSUE TITLE
Did not generate image for TP-Link TL-1041n

### ISSUE THREAD

**Issue by yy0c** [gwlim/mips74k-lede-patch#12]
I've used this patch to generate a image for my 1041n(AR9342), however I didn't find the corresponding image file. What's wrong? Or can you build one for me?

Sorry, I'm not a native English speaker.
![2017-07-28 20 11 21](https://user-images.githubusercontent.com/1238163/28716752-73fc629a-73d1-11e7-8414-f506a28a37a6.png)

**Comment by gwlim** [comment]
TP-Link WR1041n has only 4MB of flash it is not possible to generate any lede firmware unless you remove almost everything including luci

**Comment by yy0c** [comment]
@gwlim 

Already figured that out. 

Luckily I've soldered 8MB of flash on my 1041N. I can get over 500Mpbs NAT with this patch so I don't have to buy a new router. (previously less than 90Mbps, Gargoyle 1.8.1)

Best of all, this patch significantly reduced CPU load, from over 1.8 to less than 0.3, experience is very much improved. 

I must extend my gratitude to you, I feel so exciting to enjoy your work.

**Comment by gwlim** [comment]
No problem
If you have 8MB you can edit this file
/target/linux/ar71xx/image/tp-link.mk
```
--- a/target/linux/ar71xx/image/tp-link.mk
+++ b/target/linux/ar71xx/image/tp-link.mk
@@ -783,7 +783,7 @@ endef
 TARGET_DEVICES += tl-wr941nd-v2 tl-wr941nd-v3 tl-wr941nd-v4 tl-wr941nd-v5 tl-wr941nd-v6 tl-wr941nd-v6-cn tl-wr94
 
 define Device/tl-wr1041n-v2
-    $(Device/tplink-4mlzma)
+    $(Device/tplink-8mlzma)
     DEVICE_TITLE := TP-LINK TL-WR1041N
     BOARDNAME := TL-WR1041N-v2
     DEVICE_PROFILE := TLWR1041
```
