### ISSUE TITLE
Wifi isolation feature redundancy

### ISSUE THREAD

**Issue by ghost** [gwlim/mips74k-lede-patch#13]
After this upstream commit (https://github.com/openwrt/luci/commit/aee99ce92730912f21fb313953ac6b7a35a5df58) the wireless client isolation feature added in [this patch](https://github.com/gwlim/mips74k-ar71xx-lede-patch/blob/lede-17.01/patch/064-luci-wifi-add-feature.patch#L36) now seems redundant. The options appear on different tabs in luci config, but do about the same thing, so I think this can now be removed from the patch.

**Comment by gwlim** [comment]
This luci change is still not propagated to 17.01 it is still in Trunk.
Will fix when 17.01 is updated

**Comment by gwlim** [comment]
vvvvvvvvvvvvvvm,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,mmmmm,              


+++






                                                                 


\\\\
