### ISSUE TITLE
please have a look,some patch hunk cause faile

### ISSUE THREAD

**Issue by crackself** [gwlim/mips74k-lede-patch#16]
here's terminal output:
[log.txt](https://github.com/gwlim/mips74k-ar71xx-lede-patch/files/1290496/log.txt)

**Comment by gwlim** [comment]
Try again 
https://github.com/gwlim/mips74k-ar71xx-lede-patch/commit/cb5c40b9b5238c6e3f97e8ea321daabbbe451799

**Comment by crackself** [comment]
it's the lastest update for this repo,git log show:
commit cb5c40b9b5238c6e3f97e8ea321daabbbe451799
Author: gwlim <alphasparc@gmail.com>
Date:   Sat Sep 9 20:13:39 2017 +0800

    Update kernel

lede-17.01 commit is "082e6215b7cc5c823d6b0254de45420209ad68b1" is that the problem?

**Comment by gwlim** [comment]
Delete and start over.
It is already fixed by https://github.com/gwlim/mips74k-ar71xx-lede-patch/commit/cb5c40b9b5238c6e3f97e8ea321daabbbe451799

**Comment by crackself** [comment]
sloved,thanks.
