### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by rule2c** [gwlim/mips74k-lede-patch#17]
Mon Sep 18 13:50:12 2017 user.info kernel: [    8.856895] mount_root: loading kmods from internal overlay
Mon Sep 18 13:50:12 2017 user.err kernel: [    8.870839] mount_root: failed to launch kmodloader from internal overlay
Mon Sep 18 13:50:12 2017 kern.err kernel: [    9.328067] blk_update_request: I/O error, dev mtdblock4, sector 48

wndr4300
iptables-mod-tproxy can't be used.

**Comment by gwlim** [comment]
If you are using extroot it means your extroot device filesystem is either corrupted or the flash is damaged
