### ISSUE TITLE
002-mips74kc-set-optimization.patch lede-17.01 branch

### ISSUE THREAD

**Issue by ivangotoy** [gwlim/mips74k-lede-patch#2]
Is this snippet right?

CPU_TYPE:=24kc
+CPU_TYPE:=24kc

**Comment by gwlim** [comment]
It is correct, I changed to 24kc because upstream LEDE repo builds all MIPS with 24kc tag.
If you want to use upstream package you have to use MIPS24kc tag
Check my build config it still says march=74kc
Optimization is still made for 74kc but we use 24kc label because I am too lazy to maintain package repo.

**Comment by chros73** [comment]
Is it a [typo](https://github.com/gwlim/mips74k-ar71xx-lede-patch/blob/lede-17.01/patch/001-mips-cflag-optimization.patch#L23) in `001-mips-cflag-optimization.patch` file or intended? Shouldn't be `24kc`?
`CPU_CFLAGS_24kc = -march=74kc`

Thanks for your work!

**Comment by chros73** [comment]
> I changed to 24kc because upstream LEDE repo builds all MIPS with 24kc tag.

Err, isn't [this](http://downloads.lede-project.org/releases/17.01.2/packages/mipsel_74kc/) good for us?

Edit: Oh, ours is mips and not mipsel, sorry.

**Comment by gwlim** [comment]
MIPS can run on Big Endian or Little Endian
QCA mips default = be (Big Endian) 
MTK mips default = el (Endian Little)
Interesting how Atheros got bought by Qualcomm and conversely Ralink got bought by Mediatek
Notice they swap the Endian (e) position around to confer the notion of Endianess.

**Comment by chros73** [comment]
Thanks for the info, I didn't know these.

What about the potential typo?

**Comment by gwlim** [comment]
There is no typo we use lede upstream package repo which forces everything to be mips24 tagged but mips74 optimization is still applied to compiler
