### ISSUE TITLE
compile gcc failed

### ISSUE THREAD

**Issue by jack338c** [gwlim/mips74k-lede-patch#23]
same build environment,build official lede1701 is ok

thanks

/home/jack/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/mips-openwrt-linux-musl/sys-include   
checking for suffix of object files... configure: error: in `/home/jack/lede/build_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/gcc-5.4.0-initial/mips-openwrt-linux-musl/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
Makefile:10906: recipe for target 'configure-target-libgcc' failed
make[4]: *** [configure-target-libgcc] Error 1
make[4]: Leaving directory '/home/jack/lede/build_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/gcc-5.4.0-initial'
Makefile:36: recipe for target '/home/jack/lede/build_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/gcc-5.4.0-initial/.built' failed
make[3]: *** [/home/jack/lede/build_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/gcc-5.4.0-initial/.built] Error 2
make[3]: Leaving directory '/home/jack/lede/toolchain/gcc/initial'
toolchain/Makefile:91: recipe for target 'toolchain/gcc/initial/compile' failed
make[2]: *** [toolchain/gcc/initial/compile] Error 2
make[2]: Leaving directory '/home/jack/lede'
toolchain/Makefile:89: recipe for target '/home/jack/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/stamp/.toolchain_install' failed
make[1]: *** [/home/jack/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/stamp/.toolchain_install] Error 2
make[1]: Leaving directory '/home/jack/lede'
/home/jack/lede/include/toplevel.mk:205: recipe for target 'world' failed

**Comment by juppin** [comment]
I could also not compile toolchain...
Check if [PR25](https://github.com/gwlim/mips74k-ar71xx-lede-patch/pull/25) solve your issue

**Comment by jack338c** [comment]
@juppin 
many thanks
