### ISSUE TITLE
Error during compilation toolchain

### ISSUE THREAD

**Issue by bardimnik** [gwlim/mips74k-lede-patch#26]
Hello! When I compile the toolchain, I get this error:

^      
x86_64-pc-linux-gnu-g++ -fno-PIE -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc -I/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/. -I/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/../include -I/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/../libcpp/include -I/home/bardimnik/QQ/lede/staging_dir/host/include -I/home/bardimnik/QQ/lede/staging_dir/host/include -I/home/bardimnik/QQ/lede/staging_dir/host/include  -I/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/../libdecnumber -I/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/../libdecnumber/dpd -I../libdecnumber -I/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/../libbacktrace   -o ubsan.o -MT ubsan.o -MMD -MP -MF ./.deps/ubsan.TPo /home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/ubsan.c
/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/ubsan.c: In function 'bool ubsan_use_new_style_p(location_t)':
/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
       || xloc.file == '\0' || xloc.file[0] == '\xff'
                       ^~~~
make[4]: *** [Makefile:1085: ubsan.o] Error 1
make[4]: Leaving directory '/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0-initial/gcc'
make[3]: *** [Makefile:4115: all-gcc] Error 2
make[3]: Leaving directory '/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0-initial'
make[2]: *** [Makefile:37: /home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0-initial/.built] Error 2
make[2]: Leaving directory '/home/bardimnik/QQ/lede/toolchain/gcc/initial'
make[1]: *** [toolchain/Makefile:92: toolchain/gcc/initial/compile] Error 2
make[1]: Leaving directory '/home/bardimnik/QQ/lede'
make: *** [/home/bardimnik/QQ/lede/include/toplevel.mk:207: toolchain/install] Ошибка 2

Tell me, what could be the error?

**Comment by bardimnik** [comment]
Done: you need to file:
/home/bardimnik/QQ/lede/build_dir/toolchain-mips_24kc_gcc-6.3.0_musl-1.1.16/gcc-6.3.0/gcc/ubsan.c
find and fix the string:
|| xloc.file == '\0' || xloc.file[0] == '\xff'
on
|| xloc.file[0] == '\0' || xloc.file[0] == '\xff'
and start compilation again.
Found the answer here:
https://patchwork.openembedded.org/patch/138884/

**Comment by bladeoner** [comment]
I cherry picked it from the master branch, from today it's also included by default as a patch in 17.01

**Comment by bardimnik** [comment]
Thanks
