### ISSUE TITLE
patch_LEDE.sh - invalid sed file parameter

### ISSUE THREAD

**Issue by jsebosik** [gwlim/mips74k-lede-patch#3]
Hi,

in file patch_LEDE.sh on line 18 there is missing directory 'src' before Makefile
sed -i 's|+kmod-ipt-extra +kmod-ipt-filter +kmod-ipv6 |+kmod-ipt-extra +kmod-ipt-filter |g' ./package/ssdk/qca-ssdk/Makefile

Should be:
sed -i 's|+kmod-ipt-extra +kmod-ipt-filter +kmod-ipv6 |+kmod-ipt-extra +kmod-ipt-filter |g' ./package/ssdk/qca-ssdk/src/Makefile

**Comment by gwlim** [comment]
Nope this is correct check your path.
Did you run my script or did you cherry pick and assume fail because you missed out step(s)
