### ISSUE TITLE
kmod-qca-ssdk-hnat: dependency kmod-ipv6 not required

### ISSUE THREAD

**Issue by jsebosik** [gwlim/mips74k-lede-patch#5]
Hi, 

if possible please remove dependency on kmod-ipv6 package, because opkg cant build package kmod-qca-ssdk-hnat. I tried to find kmod-ipv6 package in LEDE menuconfig + also in official builds by LEDE, but didn`t found anything.

**Comment by gwlim** [comment]
The patching failed that is why you are getting this error
