### ISSUE TITLE
Patch Failed

### ISSUE THREAD

**Issue by ekenchan** [gwlim/mips74k-lede-patch#6]
Applying patch 001-mips-cflag-optimization.patch
patching file include/target.mk
Applying patch 002-mips74kc-set-optimization.patch
patching file target/linux/ar71xx/Makefile
Applying patch 003-disable-mips16-all-package.patch
patching file include/package.mk
Hunk #1 succeeded at 14 with fuzz 2 (offset 1 line).
Applying patch 004-kernel-mtune74kc.patch
patching file ./target/linux/ar71xx/patches-4.4/221-kernel-mtune-74kc.patch.patch
Applying patch 005-lzma-mips74kc-optimize.patch
patching file target/linux/ar71xx/image/lzma-loader/src/Makefile
Applying patch 006-branch-likely-optimize.patch
patching file target/linux/ar71xx/patches-4.4/222-kernel-branch-likely-74kc.patch.patch
Applying patch 007-config-image-squashfs-size.patch
patching file config/Config-images.in
Applying patch 007-config-kernel-no-symbol.patch
patching file config/Config-kernel.in
Applying patch 008-generic-kernel-options.patch
patching file target/linux/generic/config-4.4
Applying patch 008-remove-kernel-debug.patch
patching file ./target/linux/generic/patches-4.4/008-remove-kernel-debug.patch
Applying patch 009-ar71xx-kernel-options.patch
patching file target/linux/ar71xx/config-4.4
Hunk #1 succeeded at 241 (offset 2 lines).
Hunk #2 succeeded at 281 (offset 2 lines).
Hunk #3 FAILED at 289.
Hunk #4 succeeded at 312 (offset 3 lines).
Hunk #5 succeeded at 437 (offset 6 lines).
1 out of 5 hunks FAILED -- saving rejects to file target/linux/ar71xx/config-4.4.rej

**Comment by gwlim** [comment]
Check your ar71xx config.
I just did a clone and patch there was no errors
